# Generated by Django 5.2.7 on 2025-10-14 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_pedido_lineapedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creando_en',
            new_name='creado_en',
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.pedido'),
        ),
    ]
